/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    404: typeof import('./src/components/404.vue')['default']
    Avatar: typeof import('./src/components/Navigation/Avatar.vue')['default']
    ChangeTheme: typeof import('./src/components/Navigation/ChangeTheme.vue')['default']
    Footer: typeof import('./src/components/Footer/index.vue')['default']
    GradientBox: typeof import('./src/components/GradientBox/index.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld/index.vue')['default']
    IconFont: typeof import('./src/components/IconFont/index.vue')['default']
    Layout: typeof import('./src/components/Layout/index.vue')['default']
    LayoutArea: typeof import('./src/components/Layout/LayoutArea.vue')['default']
    LayoutSection: typeof import('./src/components/Layout/LayoutSection.vue')['default']
    LayoutView: typeof import('./src/components/Layout/LayoutView.vue')['default']
    LayoutWork: typeof import('./src/components/Layout/LayoutWork.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NavBar: typeof import('./src/components/Navigation/NavBar.vue')['default']
    NBreadcrumb: typeof import('naive-ui')['NBreadcrumb']
    NBreadcrumbItem: typeof import('naive-ui')['NBreadcrumbItem']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NGi: typeof import('naive-ui')['NGi']
    NGrid: typeof import('naive-ui')['NGrid']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NPageHeader: typeof import('naive-ui')['NPageHeader']
    NPopover: typeof import('naive-ui')['NPopover']
    NSpace: typeof import('naive-ui')['NSpace']
    NStatistic: typeof import('naive-ui')['NStatistic']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NThing: typeof import('naive-ui')['NThing']
    Octocat: typeof import('./src/components/Footer/octocat.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchCorporation: typeof import('./src/components/SearchSelect/SearchCorporation.vue')['default']
    SearchSelect: typeof import('./src/components/SearchSelect/index.vue')['default']
    SideAction: typeof import('./src/components/Navigation/Side/SideAction.vue')['default']
    SideGoBack: typeof import('./src/components/Navigation/Side/SideGoBack.vue')['default']
    SideLogo: typeof import('./src/components/Navigation/Side/SideLogo.vue')['default']
  }
}
